apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    app: first-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-app
          image: acrhnnonprod.azurecr.io/first-app:v1.1
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
apiVersion: v1
kind: Service
metadata:
name: first-app
spec:
selector:
app: first-app
ports:
 - protocol: TCP
port: 5000      # Exposed port for Kubernetes access
targetPort: 5000    # Port your Flask app listens on inside the container
type: ClusterIP
