apiVersion: v1
kind: Service
metadata:
  name: first-app-service
spec:
  selector:
    app: first-app
  ports:
  - protocol: TCP
    port: 4500          # Exposed port for Kubernetes access
    targetPort: 5000    # Port your Flask app listens on inside container
  type: ClusterIP
