apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    app: first-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-app
          image: your-acr-name.azurecr.io/first-app:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
